[build]
  command = "npm install && npm run build"
  publish = "agrimillet-frontend/build/web"
  functions = "agrimillet-backend"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
